[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
prediktfi_protocol = "7teE7a7WG52de1zAQUEhEoHoMKfokMi2SRkvofDyzEtR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/runner/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
