#!/bin/bash

# Manual QA Script for Intent Flow
# Tests the complete intent creation and management flow

echo "🧪 Starting Intent Flow QA Test"
echo "================================"

# Check if the dev server is running
if ! curl -s http://localhost:3000 > /dev/null; then
    echo "❌ Dev server not running. Please start with: pnpm dev"
    exit 1
fi

echo "✅ Dev server is running"

# Test 1: Create a new intent from Studio
echo ""
echo "📝 Test 1: Create Intent from Studio"
echo "------------------------------------"
echo "1. Navigate to http://localhost:3000/studio"
echo "2. Fill out the insight form with:"
echo "   - Topic: Crypto"
echo "   - Question: Will Bitcoin reach $100k by end of 2024?"
echo "   - Horizon: 30 days"
echo "3. Click 'Generate Insight'"
echo "4. Wait for analysis to complete"
echo "5. Click '🚀 Trade This Prediction'"
echo "6. Verify you're redirected to /advisor/actions"
echo "7. Check console for: '[Intent] saved <intent-id>'"
echo ""
read -p "Press Enter when you've completed Test 1..."

# Test 2: Verify intent appears on Actions page
echo ""
echo "📋 Test 2: Verify Intent on Actions Page"
echo "----------------------------------------"
echo "1. You should be on /advisor/actions"
echo "2. Verify the intent appears in 'Your Intents' section"
echo "3. Check console for: '[Intent] loaded <count>'"
echo "4. Verify intent shows:"
echo "   - Asset symbol (e.g., BTC)"
echo "   - Direction (Long/Short)"
echo "   - Probability percentage"
echo "   - Confidence percentage"
echo "   - Thesis text"
echo "   - Created date/time"
echo ""
read -p "Press Enter when you've completed Test 2..."

# Test 3: Refresh page - intent should persist
echo ""
echo "🔄 Test 3: Refresh Persistence"
echo "-----------------------------"
echo "1. Refresh the page (F5 or Cmd+R)"
echo "2. Verify the intent is still there"
echo "3. Check console for: '[Intent] loaded <count>'"
echo "4. Verify all intent data is preserved"
echo ""
read -p "Press Enter when you've completed Test 3..."

# Test 4: Navigate to Feed and back
echo ""
echo "🧭 Test 4: Navigation Persistence"
echo "--------------------------------"
echo "1. Navigate to /feed"
echo "2. Click on 'Actions' in the navigation"
echo "3. Verify the intent is still there"
echo "4. Check that all data is preserved"
echo ""
read -p "Press Enter when you've completed Test 4..."

# Test 5: Wallet connection states
echo ""
echo "🔗 Test 5: Wallet Connection States"
echo "----------------------------------"
echo "1. Disconnect your wallet (if connected)"
echo "2. Verify 'Execute' button is disabled"
echo "3. Verify intent is still visible"
echo "4. Reconnect your wallet"
echo "5. Verify 'Execute' button is enabled"
echo "6. Verify intent data is unchanged"
echo ""
read -p "Press Enter when you've completed Test 5..."

# Test 6: Create multiple intents
echo ""
echo "📊 Test 6: Multiple Intents"
echo "--------------------------"
echo "1. Go back to /studio"
echo "2. Create another intent with different parameters:"
echo "   - Topic: Stocks"
echo "   - Question: Will Tesla stock rise 20% this month?"
echo "   - Horizon: 14 days"
echo "3. Click '🚀 Trade This Prediction'"
echo "4. Verify both intents appear in 'Your Intents'"
echo "5. Verify newest intent appears first"
echo "6. Check console logs for both intents"
echo ""
read -p "Press Enter when you've completed Test 6..."

# Test 7: Intent removal
echo ""
echo "🗑️ Test 7: Intent Removal"
echo "-------------------------"
echo "1. Click the '✕' button on one of the intents"
echo "2. Verify the intent is removed from the list"
echo "3. Refresh the page"
echo "4. Verify the intent stays removed"
echo "5. Verify the other intent is still there"
echo ""
read -p "Press Enter when you've completed Test 7..."

# Test 8: Empty state
echo ""
echo "📭 Test 8: Empty State"
echo "---------------------"
echo "1. Remove all remaining intents"
echo "2. Verify empty state appears:"
echo "   - 'No Trading Intents Yet' message"
echo "   - 'Send a prediction from Studio to start trading' description"
echo "   - 'Open Studio' button"
echo "3. Verify all text is in English"
echo ""
read -p "Press Enter when you've completed Test 8..."

# Test 9: Console log verification
echo ""
echo "🔍 Test 9: Console Log Verification"
echo "----------------------------------"
echo "1. Open browser console (F12)"
echo "2. Look for the following logs:"
echo "   - '[Intent] saved <intent-id>' (when creating)"
echo "   - '[Intent] loaded <count>' (when loading)"
echo "   - '[IntentPersistence] Intent saved: {...}' (detailed logs)"
echo "3. Verify no error messages related to localStorage"
echo "4. Verify no SSR-related warnings"
echo ""
read -p "Press Enter when you've completed Test 9..."

# Test 10: Edge cases
echo ""
echo "⚠️ Test 10: Edge Cases"
echo "--------------------"
echo "1. Test with very long thesis text"
echo "2. Test with special characters in asset names"
echo "3. Test with extreme probability values (0%, 100%)"
echo "4. Test rapid creation/deletion of intents"
echo "5. Test browser back/forward navigation"
echo ""
read -p "Press Enter when you've completed Test 10..."

echo ""
echo "🎉 QA Test Complete!"
echo "==================="
echo ""
echo "Summary of what was tested:"
echo "✅ Intent creation from Studio"
echo "✅ Intent persistence across page refreshes"
echo "✅ Intent persistence across navigation"
echo "✅ Wallet connection state handling"
echo "✅ Multiple intents management"
echo "✅ Intent removal functionality"
echo "✅ Empty state display"
echo "✅ Console logging"
echo "✅ Edge cases"
echo ""
echo "If all tests passed, the intent system is working correctly!"
echo "If any tests failed, please note the issues and fix them."
