#!/bin/bash

# Smoke Test: Trading Flow
# Tests the complete Studio → Actions → Intent creation flow

echo "🧪 Smoke Test: Trading Flow"
echo "================================"
echo ""

echo "📋 Manual Test Checklist:"
echo ""

echo "1️⃣  Studio Analysis & Draft Creation"
echo "   □ Navigate to /studio"
echo "   □ Enter a prediction (e.g., 'Will Bitcoin reach \$100k by end of 2024?')"
echo "   □ Select topic: 'Crypto', horizon: '30 days'"
echo "   □ Click 'Generate Insight' and wait for analysis"
echo "   □ Verify analysis shows probability % and confidence %"
echo "   □ Click 'Save & Preview' button"
echo ""

echo "2️⃣  Save Modal & Trade Button"
echo "   □ Save modal opens with insight summary"
echo "   □ Verify 'Save & Stamp' shows disabled state with Pro hint tooltip"
echo "   □ Click '🚀 Trade This Prediction' button"
echo "   □ Check console for '[Trade] Draft created:' log entry"
echo "   □ Verify navigation to /advisor/actions?draft=1"
echo ""

echo "3️⃣  Actions Page & Composer"
echo "   □ Trading Intent Composer appears at top"
echo "   □ Verify all fields prefilled from analysis:"
echo "     - Asset symbol (BTC/ETH/SOL/etc.)"
echo "     - Direction (Long if prob >= 50%, Short if < 50%)"
echo "     - Confidence slider matches analysis"
echo "     - Probability readonly field matches analysis"
echo "     - Thesis textarea has content from rationale"
echo "     - Time horizon defaults to 30 days"
echo ""

echo "4️⃣  Intent Creation"
echo "   □ Modify any fields if desired (optional)"
echo "   □ Click 'Create Intent (Dev)' button"
echo "   □ Check console for '[Actions] Intent created:' log entry"
echo "   □ Verify toast notification appears: 'Intent created successfully!'"
echo "   □ Composer disappears"
echo "   □ Intent appears in 'Your Intents' section below"
echo ""

echo "5️⃣  Persistence Tests"
echo "   □ Refresh the /advisor/actions page"
echo "   □ Verify intent still appears in 'Your Intents' section"
echo "   □ Navigate to /studio, then back to /advisor/actions"
echo "   □ Verify intent persists across navigation"
echo "   □ Check localStorage in DevTools for 'predikt:user-intents' key"
echo ""

echo "6️⃣  Wallet Session Persistence"
echo "   □ Connect wallet in header: 'Connect Phantom' button"
echo "   □ Complete wallet connection and sign-in"
echo "   □ Navigate between /studio and /advisor/actions multiple times"
echo "   □ Verify wallet address stays visible in header (e.g., 'Ez6d...md5')"
echo "   □ Confirm no repeated sign prompts during navigation"
echo "   □ Check console for minimal wallet error spam"
echo ""

echo "7️⃣  Empty State Test"
echo "   □ Clear localStorage: 'predikt:user-intents'"
echo "   □ Navigate to /advisor/actions (without ?draft=1)"
echo "   □ Verify empty state appears with English text:"
echo "     'Send a prediction from Studio to start trading'"
echo "   □ Click 'Open Studio' button"
echo "   □ Verify navigation to /studio"
echo ""

echo "✅ Expected Console Logs:"
echo "   [Trade] Draft created: { id, asset, direction, probability, confidence }"
echo "   [Actions] Intent created: { id, asset, direction, probability, confidence, horizonDays, totalIntents }"
echo ""

echo "❌ Console Should NOT Show:"
echo "   - Repeated wallet connection errors"
echo "   - JSON parse errors"
echo "   - Multiple sign-in prompts"
echo "   - Wallet adapter spam"
echo ""

echo "🎯 Success Criteria:"
echo "   □ Complete flow works without errors"
echo "   □ Draft and intent data persists across refreshes"
echo "   □ Wallet session maintained during navigation"
echo "   □ Clean console logs (only meaningful messages)"
echo "   □ UI shows appropriate states and feedback"
echo ""

echo "📝 Notes:"
echo "   - Test in development environment"
echo "   - Use Chrome DevTools to monitor console and localStorage"
echo "   - Test with Phantom wallet installed"
echo "   - Verify responsive design on different screen sizes"
echo ""

echo "🚀 Ready to test! Open http://localhost:3000/studio to begin."
